name: autofix.ci
on:
  pull_request:
  push:
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - run: |
          yarn
          yarn prettier . --write --ignore-unknown
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
